version: "3.8"

services:
    api:
      env_file:
        - ./.env.dev 
      ports:
        - "8000:8000"

    db:
      env_file:
        - ./.env.dev
      ports:
        - "5432:5432"


    client:
      env_file:
          - ./client/.env.dev
      ports: 
          - "8080:8080"

