version: "3.8"

services:
    api:
        container_name: anime-api
        build:
            context: .
            dockerfile: ./app/Dockerfile
        restart: always
        volumes:
            - ./app:/usr/src 
        depends_on:
            - db
    db:
        image: postgres:14-alpine
        container_name: anime-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/ 
        expose:
            - 5432
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLING=true
        volumes:
            - ./client:/client
            - /client/node_modules
        
volumes:
    postgres_data:
    client:
